swagger: '2.0'

info:
  version: "0.1.0"
  title: HUB API


# Configurações Globais
host: localhost:3000
consumes: [application/json]
produces: [application/json]


paths:
  #################################
  #    A U T E N T I C A Ç Â O
  #################################
  /auth/sign_in:
    post:
      description: "Sign in"

      parameters:
        - in: body
          name: body
          description: Dados de login
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                description: email de login
              password:
                type: string
                format: password
                description: senha

      responses:
        200:
          description: Successful response
          schema:
            # title: User data
            type: object
            properties:
              data:
                type: object
                properties:
                  id: 
                    type: integer
                    format: int64
                    description: Identificador do registro
                  email:
                    type: string
                    description: Email
                  first_name:
                    type: string
                    description: Primeiro nome
                  last_name:
                    type: string
                    description: Sobrenome
                  uid:
                    type: string
                    description: identificador de usuário
                  provider:
                    type: string
                    description: provedor de autenticação
                  avatar_url:
                    type: string
                    description: URL da imagem do avatar
                  thumb_url:
                    type: string
                    description: URL do thumbnail do avatar
          headers:
            access-token:
              type: string
              description: Token de acesso a ser usado nas futuras requisições
            client:
              type: string
              description: Código do client
            expiry:
              type: string
              description: Exppiração do token
            uid:
              type: string
              description: Identificador único do usuário
            token-type:
              type: string
              description: Tipo do token. Normalmente 'Bearer'
        401:
          description: Autorização negada
          schema:
            $ref: "#/definitions/Errors"



  ######################################################
  #             C  o  m  m  u  n  i  t  y
  ######################################################
  /communities:
    post:
      description: Cria nova comunidade

      parameters:
        - in: header
          name: Token-Type
          type: string
          description: Tipo do Token - retornado pela validação (através do header)
        - in: header
          name: Access-Token
          type: string
          description: Token - retornado pela validação (através do header)
        - in: header
          name: Uid
          type: string
          description: Identificador de usuário - retornado pela validação (através do header)
        - in: header
          name: Client
          type: string
          description: Identificador de client - retornado pela validação (através do header)
        - in: body
          name: body
          description: Dados da comunidade
          required: true
          schema:
            type: object
            properties:
              community:
                type: object
                description: Dados da comunidade
                required: [name]
                properties:
                  name:
                    type: string
                    description: Nome da comunidade. Deve ser única no sistema
                  city:
                    type: string
                    description: Nome da cidade
                  mailchimp_api_key:
                    type: string
                    description: Código da api do mailchimp
                  mailchimp_list_id:
                    type: string
                    description: Identificador da lista do mailchimp
                  mailchimp_group_id:
                    type: string
                    description: Identificador do grupo do mailchimp
                  image character:
                    type: string
                    description: URL da imagem da comunidade
                  description:
                    type: string
                    description: Descrição da comunidade
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Community"
        401:
          description: Sem autorização
          schema:
            $ref: "#/definitions/Errors"
        400:
          description: Malformação da mensagem
          schema:
            $ref: "#/definitions/Errors"
            
    get:
      description: Listagem de comunidades do usuario
      parameters:
        - in: header
          name: Token-Type
          type: string
          description: Tipo do Token - retornado pela validação (através do header)
        - in: header
          name: Access-Token
          type: string
          description: Token - retornado pela validação (através do header)
        - in: header
          name: Uid
          type: string
          description: Identificador de usuário - retornado pela validação (através do header)
        - in: header
          name: Client
          type: string
          description: Identificador de client - retornado pela validação (através do header)
      responses:
        200:
          description: Listagem ok
          schema:
            description: Lista de comunidades ao qual o usuário possui acesso
            type: array
            items:
              $ref: "#/definitions/Community"
        401:
          description: Sem autorização
          schema:
            $ref: "#/definitions/Errors"


  /communities/{community_id}:
    get:
      description: Pesquisa dados da comunidade

      parameters:
        - in: header
          name: Token-Type
          type: string
          description: Tipo do Token - retornado pela validação (através do header)
        - in: header
          name: Access-Token
          type: string
          description: Token - retornado pela validação (através do header)
        - in: header
          name: Uid
          type: string
          description: Identificador de usuário - retornado pela validação (através do header)
        - in: header
          name: Client
          type: string
          description: Identificador de client - retornado pela validação (através do header)
        - in: path
          name: community_id
          type: integer
          format: int64
          required: true
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Community"
        401:
          description: Sem autorização
          schema:
            $ref: "#/definitions/Errors"
        400:
          description: Malformação da mensagem
          schema:
            $ref: "#/definitions/Errors"
    
    
    put:
      description: Cria nova comunidade

      parameters:
        - in: header
          name: Token-Type
          type: string
          description: Tipo do Token - retornado pela validação (através do header)
        - in: header
          name: Access-Token
          type: string
          description: Token - retornado pela validação (através do header)
        - in: header
          name: Uid
          type: string
          description: Identificador de usuário - retornado pela validação (através do header)
        - in: header
          name: Client
          type: string
          description: Identificador de client - retornado pela validação (através do header)
        - in: path
          name: community_id
          type: integer
          format: int64
          required: true
        - in: body
          name: body
          description: Dados da comunidade
          required: true
          schema:
            type: object
            properties:
              community:
                type: object
                description: Dados da comunidade
                required: [name]
                properties:
                  name:
                    type: string
                    description: Nome da comunidade. Deve ser única no sistema
                  city:
                    type: string
                    description: Nome da cidade
                  mailchimp_api_key:
                    type: string
                    description: Código da api do mailchimp
                  mailchimp_list_id:
                    type: string
                    description: Identificador da lista do mailchimp
                  mailchimp_group_id:
                    type: string
                    description: Identificador do grupo do mailchimp
                  image character:
                    type: string
                    description: URL da imagem da comunidade
                  description:
                    type: string
                    description: Descrição da comunidade
                  recipient:
                    description: Dados de recebedor do PagarMe
                    type: object
                    properties:
                      transfer_interval:
                        type: string
                        description: Frequência na qual o recebedor irá ser pago. 
                      transfer_day:
                        type: integer
                        format: int32
                        description: Dia no qual o recebedor vai ser pago.
                      transfer_enabled:
                        type: boolean
                        description: Variável que indica se o recebedor pode receber os pagamentos 
                      bank_account_id:
                        type: string
                        description: Identificador de uma conta bancária previamente criada. Caso você não tenha essa informação, use a propriedade bank_account.
                      bank_account:
                        type: object
                        description: Objeto contendo os dados bancários do recebedor. Este objeto, e as suas respectivas propriedades, serão obrigatórios caso não seja informado um bank_account_id.
                        properties:
                          bank_code:
                            type: string
                            description: Código do banco do recebedor
                          agencia:
                            type: string
                            description: Agência da conta do recebedor
                          conta:
                            type: string
                            description: Número da conta bancária do recebedor
                          conta_dv:
                            type: string
                            description: Dígito verificador da conta do recebedor
                          document_number:
                            type: string
                            description: CPF ou CNPJ do recebedor
                          legal_name:
                            type: string
                            description: Nome completo ou razão social do recebedor
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Community"
        401:
          description: Sem autorização
          schema:
            $ref: "#/definitions/Errors"
        400:
          description: Malformação da mensagem
          schema:
            $ref: "#/definitions/Errors"


  /communities/{community_id}/activists:
    get:
      description: Lista dos ativistas que participam da comunidade
      parameters:
        - in: path
          name: community_id
          type: integer
          format: int64
          required: true
          description: Identificador da comunidade
      responses:
        200:
          description: Chamada ok
          schema:
            type: array
            items:
              $ref: "#/definitions/AggActivist"
        401:
          description: Sem autorização
          schema:
            $ref: "#/definitions/Errors"

  /communities/{community_id}/mobilizations:
    get:
      description: Lista das mobilizações da comunidade
      parameters:
        - in: path
          name: community_id
          type: integer
          format: int64
          required: true
          description: Identificador da comunidade
      responses:
        200:
          description: Chamada ok
          schema:
            type: array
            items:
              $ref: "#/definitions/Mobilization"
        401:
          description: Sem autorização
          schema:
            $ref: "#/definitions/Errors"
  
definitions:
  Errors:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string
          
  Community:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Identificador do registro
      name:
        type: string
        description: Nome da comunidade
      city:
        type: string
        description: Nome da cidade
      mailchimp_api_key:
        type: string
        description: Chave de acesso - Mailchimp
      mailchimp_list_id:
        type: string
        description: ID da lista do mailchimp
      mailchimp_group_id:
        type: string
        description: ID do grupo - Mailchimp
      image:
        type: string
        description: URL da imagem
      description:
        type: string
        description: Descrição da comunidade
      recipient:
        type: object
        description: Dados do recebedor
        properties:
          object:
            type: string
            description: Tipo do objeto
          id:
            type: string
            description: Identificador no pagarme
          bank_account:
            type: object
            description: Dados bancários
            properties:
              object:
                type: string
                description: Tipo do objeto
              id:
                type: string
                description: Identificador dos dados bancários
              bank_code:
                type: string
                description: Código do banco do recebedor
              agencia:
                type: string
                description: Agência da conta do recebedor
              agencia_dv:
                type: string
                description: Dígito verificado da agência
              conta:
                type: string
                description: Número da conta bancária do recebedor
              conta_dv:
                type: string
                description: Dígito verificador da conta do recebedor
              document_type:
                type: string
                description: CPF/CNPJ
              document_number:
                type: string
                description: CPF ou CNPJ do recebedor
              legal_name:
                type: string
                description: Nome completo ou razão social do recebedor
              charge_transfer_fees:
                type: boolean
              date_created:
                type: string
                format: date-time
                description: Data de criação do registro
          transfer_enabled:
            type: boolean
            description: Variável que indica se o recebedor pode receber os pagamentos 
          last_transfer:
            type: string
            format: date-time
            description: Data da última transferência
          transfer_interval:
            type: string
            description: Frequência na qual o recebedor irá ser pago. 
          transfer_day:
            type: integer
            format: int32
            description: Dia no qual o recebedor vai ser pago.
          automatic_anticipation_enabled:
            type: boolean
            description: Se antecipação de pagamento está habilitada
          anticipatable_volume_percentage:
            type: integer
            format: int32
            description:  Porcentagem sobre o volume antecipado
          date_created:
            type: string
            format: date-time
            description: Data de criação do registro
          date_updated:
            type: string
            format: date-time
            description: Data da última atualização do registro

  Mobilization:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Identificador da mobilização
      name:
        type: string
        description: Nome da mobilização
      created_at:
        type: string
        format: date-time
        description: Data da criação
      updated_at:
        type: string
        format: date-time
        description: Data da última atualização
      user_id:
        type: integer
        format: int64
        description: Identificador do usuário
      color_scheme:
        type: string
        description: Nome da mobilização
      google_analytics_code:
        type: string
        description: Esquema de cores
      goal:
        type: string
        description: Objetivo
      facebook_share_title:
        type: string
        description: Título no facebook
      facebook_share_description:
        type: string
        description: Descrição no compartilhamento no facebook
      header_font:
        type: string
        description: Fonte do cabeçalho
      body_font:
        type: string
        description: Fonte do corpo
      facebook_share_image:
        type: string
        description: URL da imagem de compartilhamento no facebook
      slug:
        type: string
        description: parte integrante da URL amigável
      custom_domain:
        type: string
        description: Domínio
      twitter_share_text:
        type: string
        description: Texto de compartilhamento no twitter
      community_id:
        type: integer
        format: int64
        description: Identificador da comunidade

  AggActivist:
    description: Ativistas agregados
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Identificador do ativista
      email:
        type: string
        description: Email do ativista
      name:
        type: string
        description: Nome do ativista
      phone:
        type: string
        description: Telefone do ativista
      total_form_entries:
        type: integer
        format: int64
        description: Total de assinaturas em form entries
      total_donations:
        type: integer
        format: int64
        description: Total de doações
      total_pressures:
        type: integer
        format: int64
        description: Total de pressões que participou
      last_donation_status:
        type: string
        description: Status da última doação
      last_donation_amount:
        type: integer
        format: int32
        description: Total da última doação
      last_donation_is_subscription:
        type: boolean
        description: se ultima doação é subscrição