pipeline:
  build:
    image: ruby:2.3.0-onbuild
    commands:
      - ./bin/rake db:migrate
      - ./bin/bundle exec rspec spec
    services:
      database:
        - postgres
      queue:
        - redis
    cache:
      - /tmp/bundler
    enviroment:
      - RAILS_ENV=test
  publish-staging:
    image: plugins/docker
    repo: nossas/bonde-server
    username: lpirola
    password: ${DOCKER_PASSWORD}
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]
  deploy-staging:
    image: appleboy/drone-ssh
    host: staging.bonde.org
    username: ubuntu
    port: 22
    script:
      - sudo docker pull nossas/bonde-server:${DRONE_BRANCH}
      - sudo docker tag nossas/bonde-server:${DRONE_BRANCH} dokku/server:${DRONE_BRANCH}
      - dokku tags:deploy server ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
