language: ruby
rvm:
- 2.3.0
before_script:
- cp config/database.sample.yml config/database.yml
- psql -c 'create role hub SUPERUSER LOGIN;' postgres
- psql -c 'create database hub_api_test;' -U hub postgres
script: bundle exec rake db:migrate && bundle exec rspec spec
services:
- redis-server
branches:
  only:
  - master
  - dev
deploy:
  matrix:
  - provider: heroku
    app: hub-api
    on:
      repo: ourcities/hub-api
    run: rake db:migrate
  - provider: heroku
    app: hub-api-staging
    on:
      repo: ourcities/hub-api
      branch: dev
    run: rake db:migrate
  api_key:
    secure: RqoB2NEHejm0Nus1XMu93dzZKD8GBboqRCEYHwlbB3J3Y5g8PvIi0v5e5Q257O4yWIDl22Bps1OrevdHxSgTx9dk0534DL/j19owcwRALbfE48nh1tcmgov1iw0dHu1nsVnbDi+lHs1tZKYi+23Q+tE4XpBC44QZQ3GgZlChNgm+i5T4oaFeET8yc3LYeHZIJKsPClMEoqQAnmQU5W1n7moluNT1TCYl/IYpigSiM9QHHQwa/2mG4Yw7oG0F1dok28UXdweK9sv5+4m59oaMritZNb+WyqyW0wfVxk4iNTSkbaEBdvFEzMpWuZEGHyyJXHcXyG5eksEDedDBfg+3qrMHxv5l7fI7gn0DC3v82DKdQVyGA8dqJa49kwa1NHAqehbwT92ImEJzmgz0l/vj3IaCVBT4fvZHKal1BB18+PlvTuV8fB+PmIY0Hc/v107IcxZD4CQ4a7iBOobqsdBcdHT20SflF5YcGgKImUbFGwMSRoD6fXxX8B5Gz++LJJsyEkQOVYzHjuHG7fcvqC2L95sodk1qNq3NrHDm3tlGRRFH6Hup8CxIvmBlH5yF94tLBiOAkjRrkVis09jotpgv4TPcwTiDe0psC66Ns0rRklsTbf0biQujiYeLxxw+KROGGUH/3PInnxFx7WsXzlU0MfunO8U6UDnAhOnepeBoCKk=
